# Implementation of Dissimilarity Metric

## Requirements

Definition by Fang et al. (2010):

![Definition of dissimilarity index](img/dissimilarity_definition.png)

## Example

In [1]:
DIM = 5
NUM_HUMANS = 4

In [2]:
import numpy as np

def random_beliefs(dim):
    return np.random.randint(-1, 2, dim)

In [3]:
humans = np.vstack([random_beliefs(DIM) for _ in range(NUM_HUMANS)])
humans

array([[-1, -1,  1,  0,  1],
       [-1, -1,  1, -1, -1],
       [ 1, -1,  1,  1,  1],
       [-1,  0,  1,  1,  1]])

## Implementation

In [4]:
rows, cols = np.triu_indices(NUM_HUMANS, 1)

In [5]:
rows

array([0, 0, 0, 1, 1, 2])

In [6]:
cols

array([1, 2, 3, 2, 3, 3])

In [7]:
humans[rows]

array([[-1, -1,  1,  0,  1],
       [-1, -1,  1,  0,  1],
       [-1, -1,  1,  0,  1],
       [-1, -1,  1, -1, -1],
       [-1, -1,  1, -1, -1],
       [ 1, -1,  1,  1,  1]])

In [8]:
humans[cols]

array([[-1, -1,  1, -1, -1],
       [ 1, -1,  1,  1,  1],
       [-1,  0,  1,  1,  1],
       [ 1, -1,  1,  1,  1],
       [-1,  0,  1,  1,  1],
       [-1,  0,  1,  1,  1]])

In [9]:
comp = humans[rows] != humans[cols]
comp

array([[False, False, False,  True,  True],
       [ True, False, False,  True, False],
       [False,  True, False,  True, False],
       [ True, False, False,  True,  True],
       [False,  True, False,  True,  True],
       [ True,  True, False, False, False]])

In [10]:
comp_sum = np.sum(comp)
comp_sum

14

In [11]:
comp_sum * (2/(DIM*NUM_HUMANS*(NUM_HUMANS-1)))

0.4666666666666667

In [12]:
def calc_dissim(model):
    num_humans = model.conf["num_humans"]
    num_dims = model.conf["belief_dims"]
    humans = model.schedule.agents[2:(2 + num_humans)]
    beliefs = np.vstack([h.state for h in humans])
    rows, cols = np.triu_indices(num_humans, 1)
    comp_sum = np.sum(beliefs[rows] != beliefs[cols])
    coeff = 2 / (num_dims * num_humans * (num_humans - 1))
    return coeff * comp_sum

In [13]:
humans[:,2]

array([1, 1, 1, 1])

In [14]:
code = [1,1,1,1,1]

In [22]:
np.sum(humans == code

TypeError: 'function' object is not subscriptable